CREATE DATABASE laza_db;

create table app_users
(
    id        integer generated by default as identity
        primary key,
    email     varchar(255),
    full_name varchar(255),
    password  varchar(255)
);

create table roles
(
    id   bigint generated by default as identity
        primary key,

    name varchar(255) not null
        constraint unique
);

create table user_roles
(
    user_id integer not null
    constraint user_fk foreign key (user_id) references app_users (id) on delete cascade on update cascade,
    role_id bigint  not null
        constraint role_fk foreign key (role_id) references roles (id) on delete cascade on update cascade
);


create table react
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);

CREATE TABLE reaction (
                          reaction_id BIGINT AUTO_INCREMENT PRIMARY KEY,
                          post_id BIGINT NOT NULL,
                          react_id BIGINT NOT NULL,
                          user_owner_id BIGINT NOT NULL,
                          user_react_id BIGINT NOT NULL,
                          FOREIGN KEY (post_id) REFERENCES post(post_id),
                          FOREIGN KEY (react_id) REFERENCES react(react_id),
                          FOREIGN KEY (user_owner_id) REFERENCES app_user(user_id),
                          FOREIGN KEY (user_react_id) REFERENCES app_user(user_id)
);

